### ISSUE TITLE
can search functionality box be implemented? Similar to this https://github.com/christianmatei/git-playbook

### ISSUE THREAD

**Issue by christianmatei** [sunainapai/makesite#16]

**Comment by sunainapai** [comment]
Hi @christianmatei , There is no plan to implement search functionality in `makesite.py`.  I want to keep this project as simple as possible as this project is only meant to be a quick-starter-kit for developers who want to develop their own static site generators. One is free to modify, enhance, and maintain it in their own repository. This project is meant for developers who may dive into the code and enhance it for their needs (say a search functionality). An example website source is provided to get started quickly and then modify it as necessary.
