### ISSUE TITLE
You should change the front matter language

### ISSUE THREAD

**Issue by sharadcodes** [sunainapai/makesite#20]
You should change the front matter language to YML as it is used by most of the CMS for the SSGs

**Comment by sharadcodes** [comment]
I was making a netlify CMS stater for this SSG and the front matter have a problem there as you are using 

`<!-- key: value -->`

It wont work there

**Comment by sunainapai** [comment]
Hi @sharadcodes,

There are no plans to change the front matter language. You are free to add support for front matter language of your choice in your own fork.

I want to keep this project as simple as possible as this project is only meant to be a quick-starter-kit for developers who want to develop their own static site generators. I do not want to add a dependency on PyYAML in this case. However, someone forking this repo may do so and customize this project as per their needs.
