### ISSUE TITLE
How to add an image folder?

### ISSUE THREAD

**Issue by kgashok** [sunainapai/makesite#22]
@sunainapai I know you are not interested in adding any features, but what is the quickest way that I can create an image folder for me to link to images in my markdown files?

**Comment by oscarbenedito** [comment]
Just put them on the static folder (i.e. put the file on "static/path/to/image.png" and link to "/path/to/image.png" on your markdown files).

**Comment by sunainapai** [comment]
Thanks @oscarbenedito for answering this question.
